image: cirrusci/flutter:latest
pipelines:
  default:
    - step:
        name: Build and Deploy
        script:
          - flutter pub get
          - flutter build web
          - pipe: atlassian/git-lfs:0.1.0
          - git add build/web
          - git commit -m "Deploying to Bitbucket Pages"
          - git push origin master:gh-pages