/// Represents an NFL player available for drafting.
class Player {
  const Player({
    required this.id,
    required this.name,
    required this.position,
    required this.team,
    required this.rank,
    this.byeWeek = 0,
  });

  final String id;
  final String name;
  final String position;
  final String team;
  final int rank;
  final int byeWeek;

  Map<String, dynamic> toMap() => {
        'id': id,
        'name': name,
        'position': position,
        'team': team,
        'rank': rank,
        'byeWeek': byeWeek,
      };

  factory Player.fromMap(Map<String, dynamic> map) => Player(
        id: map['id'] ?? '',
        name: map['name'] ?? '',
        position: map['position'] ?? '',
        team: map['team'] ?? '',
        rank: map['rank'] ?? 0,
        byeWeek: map['byeWeek'] ?? 0,
      );
}

/// 2025 NFL player pool for drafting — 500 players.
class PlayerPool {
  static const List<Player> players = [
    // ─── Quarterbacks (32) ─────────────────────────────────────────
    Player(id: 'qb1', name: 'Patrick Mahomes', position: 'QB', team: 'KC', rank: 1, byeWeek: 6),
    Player(id: 'qb2', name: 'Josh Allen', position: 'QB', team: 'BUF', rank: 8, byeWeek: 12),
    Player(id: 'qb3', name: 'Jalen Hurts', position: 'QB', team: 'PHI', rank: 12, byeWeek: 14),
    Player(id: 'qb4', name: 'Lamar Jackson', position: 'QB', team: 'BAL', rank: 18, byeWeek: 14),
    Player(id: 'qb5', name: 'Joe Burrow', position: 'QB', team: 'CIN', rank: 35, byeWeek: 12),
    Player(id: 'qb6', name: 'CJ Stroud', position: 'QB', team: 'HOU', rank: 45, byeWeek: 14),
    Player(id: 'qb7', name: 'Dak Prescott', position: 'QB', team: 'DAL', rank: 60, byeWeek: 7),
    Player(id: 'qb8', name: 'Tua Tagovailoa', position: 'QB', team: 'MIA', rank: 75, byeWeek: 6),
    Player(id: 'qb9', name: 'Jordan Love', position: 'QB', team: 'GB', rank: 80, byeWeek: 10),
    Player(id: 'qb10', name: 'Anthony Richardson', position: 'QB', team: 'IND', rank: 90, byeWeek: 14),
    Player(id: 'qb11', name: 'Jayden Daniels', position: 'QB', team: 'WAS', rank: 95, byeWeek: 14),
    Player(id: 'qb12', name: 'Caleb Williams', position: 'QB', team: 'CHI', rank: 100, byeWeek: 7),
    Player(id: 'qb13', name: 'Brock Purdy', position: 'QB', team: 'SF', rank: 110, byeWeek: 9),
    Player(id: 'qb14', name: 'Drake Maye', position: 'QB', team: 'NE', rank: 125, byeWeek: 14),
    Player(id: 'qb15', name: 'Trevor Lawrence', position: 'QB', team: 'JAX', rank: 135, byeWeek: 12),
    Player(id: 'qb16', name: 'Kyler Murray', position: 'QB', team: 'ARI', rank: 145, byeWeek: 11),
    Player(id: 'qb17', name: 'Jared Goff', position: 'QB', team: 'DET', rank: 155, byeWeek: 5),
    Player(id: 'qb18', name: 'Matthew Stafford', position: 'QB', team: 'LAR', rank: 170, byeWeek: 6),
    Player(id: 'qb19', name: 'Kirk Cousins', position: 'QB', team: 'ATL', rank: 185, byeWeek: 12),
    Player(id: 'qb20', name: 'Sam Darnold', position: 'QB', team: 'MIN', rank: 200, byeWeek: 6),
    Player(id: 'qb21', name: 'Baker Mayfield', position: 'QB', team: 'TB', rank: 215, byeWeek: 11),
    Player(id: 'qb22', name: 'Geno Smith', position: 'QB', team: 'SEA', rank: 230, byeWeek: 10),
    Player(id: 'qb23', name: 'Derek Carr', position: 'QB', team: 'NO', rank: 250, byeWeek: 12),
    Player(id: 'qb24', name: 'Justin Fields', position: 'QB', team: 'PIT', rank: 270, byeWeek: 9),
    Player(id: 'qb25', name: 'Daniel Jones', position: 'QB', team: 'NYG', rank: 300, byeWeek: 11),
    Player(id: 'qb26', name: 'Bryce Young', position: 'QB', team: 'CAR', rank: 320, byeWeek: 11),
    Player(id: 'qb27', name: 'Deshaun Watson', position: 'QB', team: 'CLE', rank: 340, byeWeek: 10),
    Player(id: 'qb28', name: 'Russell Wilson', position: 'QB', team: 'PIT', rank: 360, byeWeek: 9),
    Player(id: 'qb29', name: 'Bo Nix', position: 'QB', team: 'DEN', rank: 380, byeWeek: 14),
    Player(id: 'qb30', name: 'Aidan O\'Connell', position: 'QB', team: 'LV', rank: 400, byeWeek: 10),
    Player(id: 'qb31', name: 'Will Levis', position: 'QB', team: 'TEN', rank: 420, byeWeek: 5),
    Player(id: 'qb32', name: 'Gardner Minshew', position: 'QB', team: 'LV', rank: 450, byeWeek: 10),
    // ─── Running Backs (80) ──────────────────────────────────────────
    Player(id: 'rb1', name: 'Christian McCaffrey', position: 'RB', team: 'SF', rank: 2, byeWeek: 9),
    Player(id: 'rb2', name: 'Bijan Robinson', position: 'RB', team: 'ATL', rank: 3, byeWeek: 12),
    Player(id: 'rb3', name: 'Breece Hall', position: 'RB', team: 'NYJ', rank: 6, byeWeek: 12),
    Player(id: 'rb4', name: 'Jahmyr Gibbs', position: 'RB', team: 'DET', rank: 9, byeWeek: 5),
    Player(id: 'rb5', name: 'Saquon Barkley', position: 'RB', team: 'PHI', rank: 11, byeWeek: 14),
    Player(id: 'rb6', name: 'Jonathan Taylor', position: 'RB', team: 'IND', rank: 15, byeWeek: 14),
    Player(id: 'rb7', name: 'Derrick Henry', position: 'RB', team: 'BAL', rank: 20, byeWeek: 14),
    Player(id: 'rb8', name: 'Travis Etienne', position: 'RB', team: 'JAX', rank: 25, byeWeek: 12),
    Player(id: 'rb9', name: 'De\'Von Achane', position: 'RB', team: 'MIA', rank: 28, byeWeek: 6),
    Player(id: 'rb10', name: 'Isiah Pacheco', position: 'RB', team: 'KC', rank: 38, byeWeek: 6),
    Player(id: 'rb11', name: 'Josh Jacobs', position: 'RB', team: 'GB', rank: 42, byeWeek: 10),
    Player(id: 'rb12', name: 'Kyren Williams', position: 'RB', team: 'LAR', rank: 48, byeWeek: 6),
    Player(id: 'rb13', name: 'Kenneth Walker III', position: 'RB', team: 'SEA', rank: 52, byeWeek: 10),
    Player(id: 'rb14', name: 'James Cook', position: 'RB', team: 'BUF', rank: 56, byeWeek: 12),
    Player(id: 'rb15', name: 'Rachaad White', position: 'RB', team: 'TB', rank: 62, byeWeek: 11),
    Player(id: 'rb16', name: 'Najee Harris', position: 'RB', team: 'PIT', rank: 68, byeWeek: 9),
    Player(id: 'rb17', name: 'Jonathon Brooks', position: 'RB', team: 'CAR', rank: 72, byeWeek: 11),
    Player(id: 'rb18', name: 'David Montgomery', position: 'RB', team: 'DET', rank: 78, byeWeek: 5),
    Player(id: 'rb19', name: 'Zamir White', position: 'RB', team: 'LV', rank: 82, byeWeek: 10),
    Player(id: 'rb20', name: 'Rhamondre Stevenson', position: 'RB', team: 'NE', rank: 88, byeWeek: 14),
    Player(id: 'rb21', name: 'Tony Pollard', position: 'RB', team: 'TEN', rank: 92, byeWeek: 5),
    Player(id: 'rb22', name: 'Javonte Williams', position: 'RB', team: 'DEN', rank: 98, byeWeek: 14),
    Player(id: 'rb23', name: 'Zack Moss', position: 'RB', team: 'CIN', rank: 105, byeWeek: 12),
    Player(id: 'rb24', name: 'Aaron Jones', position: 'RB', team: 'MIN', rank: 112, byeWeek: 6),
    Player(id: 'rb25', name: 'Brian Robinson Jr.', position: 'RB', team: 'WAS', rank: 118, byeWeek: 14),
    Player(id: 'rb26', name: 'Jerome Ford', position: 'RB', team: 'CLE', rank: 122, byeWeek: 10),
    Player(id: 'rb27', name: 'Jaylen Warren', position: 'RB', team: 'PIT', rank: 128, byeWeek: 9),
    Player(id: 'rb28', name: 'Tyjae Spears', position: 'RB', team: 'TEN', rank: 132, byeWeek: 5),
    Player(id: 'rb29', name: 'D\'Andre Swift', position: 'RB', team: 'CHI', rank: 138, byeWeek: 7),
    Player(id: 'rb30', name: 'Chuba Hubbard', position: 'RB', team: 'CAR', rank: 142, byeWeek: 11),
    Player(id: 'rb31', name: 'Gus Edwards', position: 'RB', team: 'LAC', rank: 148, byeWeek: 5),
    Player(id: 'rb32', name: 'Rico Dowdle', position: 'RB', team: 'DAL', rank: 152, byeWeek: 7),
    Player(id: 'rb33', name: 'Trey Benson', position: 'RB', team: 'ARI', rank: 158, byeWeek: 11),
    Player(id: 'rb34', name: 'Chase Brown', position: 'RB', team: 'CIN', rank: 162, byeWeek: 12),
    Player(id: 'rb35', name: 'Tyler Allgeier', position: 'RB', team: 'ATL', rank: 168, byeWeek: 12),
    Player(id: 'rb36', name: 'Deuce Vaughn', position: 'RB', team: 'DAL', rank: 172, byeWeek: 7),
    Player(id: 'rb37', name: 'Raheem Mostert', position: 'RB', team: 'MIA', rank: 178, byeWeek: 6),
    Player(id: 'rb38', name: 'Alexander Mattison', position: 'RB', team: 'LV', rank: 182, byeWeek: 10),
    Player(id: 'rb39', name: 'Bucky Irving', position: 'RB', team: 'TB', rank: 188, byeWeek: 11),
    Player(id: 'rb40', name: 'Ty Chandler', position: 'RB', team: 'MIN', rank: 192, byeWeek: 6),
    Player(id: 'rb41', name: 'Khalil Herbert', position: 'RB', team: 'CHI', rank: 198, byeWeek: 7),
    Player(id: 'rb42', name: 'Samaje Perine', position: 'RB', team: 'DEN', rank: 205, byeWeek: 14),
    Player(id: 'rb43', name: 'AJ Dillon', position: 'RB', team: 'GB', rank: 212, byeWeek: 10),
    Player(id: 'rb44', name: 'Ezekiel Elliott', position: 'RB', team: 'DAL', rank: 218, byeWeek: 7),
    Player(id: 'rb45', name: 'James Conner', position: 'RB', team: 'ARI', rank: 225, byeWeek: 11),
    Player(id: 'rb46', name: 'Nick Chubb', position: 'RB', team: 'CLE', rank: 232, byeWeek: 10),
    Player(id: 'rb47', name: 'Kareem Hunt', position: 'RB', team: 'CLE', rank: 238, byeWeek: 10),
    Player(id: 'rb48', name: 'Clyde Edwards-Helaire', position: 'RB', team: 'KC', rank: 245, byeWeek: 6),
    Player(id: 'rb49', name: 'Roschon Johnson', position: 'RB', team: 'CHI', rank: 252, byeWeek: 7),
    Player(id: 'rb50', name: 'Tank Bigsby', position: 'RB', team: 'JAX', rank: 258, byeWeek: 12),
    Player(id: 'rb51', name: 'Zach Charbonnet', position: 'RB', team: 'SEA', rank: 265, byeWeek: 10),
    Player(id: 'rb52', name: 'Antonio Gibson', position: 'RB', team: 'NE', rank: 272, byeWeek: 14),
    Player(id: 'rb53', name: 'Dameon Pierce', position: 'RB', team: 'HOU', rank: 280, byeWeek: 14),
    Player(id: 'rb54', name: 'Elijah Mitchell', position: 'RB', team: 'SF', rank: 288, byeWeek: 9),
    Player(id: 'rb55', name: 'Keaton Mitchell', position: 'RB', team: 'BAL', rank: 295, byeWeek: 14),
    Player(id: 'rb56', name: 'MarShawn Lloyd', position: 'RB', team: 'GB', rank: 302, byeWeek: 10),
    Player(id: 'rb57', name: 'Ray Davis', position: 'RB', team: 'BUF', rank: 310, byeWeek: 12),
    Player(id: 'rb58', name: 'Jaylen Wright', position: 'RB', team: 'MIA', rank: 318, byeWeek: 6),
    Player(id: 'rb59', name: 'Blake Corum', position: 'RB', team: 'LAR', rank: 325, byeWeek: 6),
    Player(id: 'rb60', name: 'Audric Estime', position: 'RB', team: 'DEN', rank: 332, byeWeek: 14),
    Player(id: 'rb61', name: 'Kendre Miller', position: 'RB', team: 'NO', rank: 340, byeWeek: 12),
    Player(id: 'rb62', name: 'Jaleel McLaughlin', position: 'RB', team: 'DEN', rank: 348, byeWeek: 14),
    Player(id: 'rb63', name: 'Cordarrelle Patterson', position: 'RB', team: 'ATL', rank: 355, byeWeek: 12),
    Player(id: 'rb64', name: 'Israel Abanikanda', position: 'RB', team: 'NYJ', rank: 362, byeWeek: 12),
    Player(id: 'rb65', name: 'Pierre Strong Jr.', position: 'RB', team: 'CLE', rank: 370, byeWeek: 10),
    Player(id: 'rb66', name: 'Emari Demercado', position: 'RB', team: 'ARI', rank: 378, byeWeek: 11),
    Player(id: 'rb67', name: 'Sean Tucker', position: 'RB', team: 'TB', rank: 385, byeWeek: 11),
    Player(id: 'rb68', name: 'Chris Rodriguez Jr.', position: 'RB', team: 'WAS', rank: 392, byeWeek: 14),
    Player(id: 'rb69', name: 'Miles Sanders', position: 'RB', team: 'CAR', rank: 400, byeWeek: 11),
    Player(id: 'rb70', name: 'Cam Akers', position: 'RB', team: 'HOU', rank: 408, byeWeek: 14),
    Player(id: 'rb71', name: 'Justice Hill', position: 'RB', team: 'BAL', rank: 415, byeWeek: 14),
    Player(id: 'rb72', name: 'Ty Johnson', position: 'RB', team: 'BUF', rank: 422, byeWeek: 12),
    Player(id: 'rb73', name: 'Jerick McKinnon', position: 'RB', team: 'KC', rank: 430, byeWeek: 6),
    Player(id: 'rb74', name: 'D\'Onta Foreman', position: 'RB', team: 'CLE', rank: 438, byeWeek: 10),
    Player(id: 'rb75', name: 'Kenneth Gainwell', position: 'RB', team: 'PHI', rank: 442, byeWeek: 14),
    Player(id: 'rb76', name: 'Deon Jackson', position: 'RB', team: 'IND', rank: 448, byeWeek: 14),
    Player(id: 'rb77', name: 'Patrick Taylor', position: 'RB', team: 'GB', rank: 455, byeWeek: 10),
    Player(id: 'rb78', name: 'Jordan Mason', position: 'RB', team: 'SF', rank: 460, byeWeek: 9),
    Player(id: 'rb79', name: 'Hassan Haskins', position: 'RB', team: 'TEN', rank: 468, byeWeek: 5),
    Player(id: 'rb80', name: 'Dare Ogunbowale', position: 'RB', team: 'HOU', rank: 475, byeWeek: 14),
    // ─── Wide Receivers (150) ────────────────────────────────────────
    Player(id: 'wr1', name: 'CeeDee Lamb', position: 'WR', team: 'DAL', rank: 4, byeWeek: 7),
    Player(id: 'wr2', name: 'Tyreek Hill', position: 'WR', team: 'MIA', rank: 7, byeWeek: 6),
    Player(id: 'wr3', name: 'Ja\'Marr Chase', position: 'WR', team: 'CIN', rank: 10, byeWeek: 12),
    Player(id: 'wr4', name: 'Amon-Ra St. Brown', position: 'WR', team: 'DET', rank: 13, byeWeek: 5),
    Player(id: 'wr5', name: 'A.J. Brown', position: 'WR', team: 'PHI', rank: 16, byeWeek: 14),
    Player(id: 'wr6', name: 'Garrett Wilson', position: 'WR', team: 'NYJ', rank: 19, byeWeek: 12),
    Player(id: 'wr7', name: 'Davante Adams', position: 'WR', team: 'NYJ', rank: 22, byeWeek: 12),
    Player(id: 'wr8', name: 'Puka Nacua', position: 'WR', team: 'LAR', rank: 26, byeWeek: 6),
    Player(id: 'wr9', name: 'Chris Olave', position: 'WR', team: 'NO', rank: 30, byeWeek: 12),
    Player(id: 'wr10', name: 'DeVonta Smith', position: 'WR', team: 'PHI', rank: 34, byeWeek: 14),
    Player(id: 'wr11', name: 'Brandon Aiyuk', position: 'WR', team: 'SF', rank: 37, byeWeek: 9),
    Player(id: 'wr12', name: 'DK Metcalf', position: 'WR', team: 'SEA', rank: 40, byeWeek: 10),
    Player(id: 'wr13', name: 'Nico Collins', position: 'WR', team: 'HOU', rank: 44, byeWeek: 14),
    Player(id: 'wr14', name: 'Malik Nabers', position: 'WR', team: 'NYG', rank: 47, byeWeek: 11),
    Player(id: 'wr15', name: 'Mike Evans', position: 'WR', team: 'TB', rank: 50, byeWeek: 11),
    Player(id: 'wr16', name: 'Marvin Harrison Jr.', position: 'WR', team: 'ARI', rank: 54, byeWeek: 11),
    Player(id: 'wr17', name: 'Drake London', position: 'WR', team: 'ATL', rank: 58, byeWeek: 12),
    Player(id: 'wr18', name: 'Stefon Diggs', position: 'WR', team: 'HOU', rank: 63, byeWeek: 14),
    Player(id: 'wr19', name: 'DJ Moore', position: 'WR', team: 'CHI', rank: 67, byeWeek: 7),
    Player(id: 'wr20', name: 'Terry McLaurin', position: 'WR', team: 'WAS', rank: 71, byeWeek: 14),
    Player(id: 'wr21', name: 'Jaylen Waddle', position: 'WR', team: 'MIA', rank: 76, byeWeek: 6),
    Player(id: 'wr22', name: 'Cooper Kupp', position: 'WR', team: 'LAR', rank: 79, byeWeek: 6),
    Player(id: 'wr23', name: 'Keenan Allen', position: 'WR', team: 'CHI', rank: 84, byeWeek: 7),
    Player(id: 'wr24', name: 'George Pickens', position: 'WR', team: 'PIT', rank: 89, byeWeek: 9),
    Player(id: 'wr25', name: 'Rashee Rice', position: 'WR', team: 'KC', rank: 93, byeWeek: 6),
    Player(id: 'wr26', name: 'Tank Dell', position: 'WR', team: 'HOU', rank: 97, byeWeek: 14),
    Player(id: 'wr27', name: 'Zay Flowers', position: 'WR', team: 'BAL', rank: 101, byeWeek: 14),
    Player(id: 'wr28', name: 'Calvin Ridley', position: 'WR', team: 'TEN', rank: 106, byeWeek: 5),
    Player(id: 'wr29', name: 'Courtland Sutton', position: 'WR', team: 'DEN', rank: 111, byeWeek: 14),
    Player(id: 'wr30', name: 'Christian Kirk', position: 'WR', team: 'JAX', rank: 115, byeWeek: 12),
    Player(id: 'wr31', name: 'Diontae Johnson', position: 'WR', team: 'CAR', rank: 119, byeWeek: 11),
    Player(id: 'wr32', name: 'Michael Pittman Jr.', position: 'WR', team: 'IND', rank: 123, byeWeek: 14),
    Player(id: 'wr33', name: 'Rome Odunze', position: 'WR', team: 'CHI', rank: 127, byeWeek: 7),
    Player(id: 'wr34', name: 'Ladd McConkey', position: 'WR', team: 'LAC', rank: 131, byeWeek: 5),
    Player(id: 'wr35', name: 'Jameson Williams', position: 'WR', team: 'DET', rank: 136, byeWeek: 5),
    Player(id: 'wr36', name: 'Quentin Johnston', position: 'WR', team: 'LAC', rank: 140, byeWeek: 5),
    Player(id: 'wr37', name: 'Josh Downs', position: 'WR', team: 'IND', rank: 144, byeWeek: 14),
    Player(id: 'wr38', name: 'Jaxon Smith-Njigba', position: 'WR', team: 'SEA', rank: 149, byeWeek: 10),
    Player(id: 'wr39', name: 'Xavier Worthy', position: 'WR', team: 'KC', rank: 153, byeWeek: 6),
    Player(id: 'wr40', name: 'Wan\'Dale Robinson', position: 'WR', team: 'NYG', rank: 157, byeWeek: 11),
    Player(id: 'wr41', name: 'Darnell Mooney', position: 'WR', team: 'ATL', rank: 161, byeWeek: 12),
    Player(id: 'wr42', name: 'Adam Thielen', position: 'WR', team: 'CAR', rank: 165, byeWeek: 11),
    Player(id: 'wr43', name: 'Brandin Cooks', position: 'WR', team: 'DAL', rank: 169, byeWeek: 7),
    Player(id: 'wr44', name: 'Curtis Samuel', position: 'WR', team: 'BUF', rank: 173, byeWeek: 12),
    Player(id: 'wr45', name: 'Rashod Bateman', position: 'WR', team: 'BAL', rank: 177, byeWeek: 14),
    Player(id: 'wr46', name: 'Tyler Lockett', position: 'WR', team: 'SEA', rank: 181, byeWeek: 10),
    Player(id: 'wr47', name: 'Jerry Jeudy', position: 'WR', team: 'CLE', rank: 186, byeWeek: 10),
    Player(id: 'wr48', name: 'Michael Thomas', position: 'WR', team: 'NO', rank: 190, byeWeek: 12),
    Player(id: 'wr49', name: 'Jakobi Meyers', position: 'WR', team: 'LV', rank: 195, byeWeek: 10),
    Player(id: 'wr50', name: 'Khalil Shakir', position: 'WR', team: 'BUF', rank: 199, byeWeek: 12),
    Player(id: 'wr51', name: 'DeAndre Hopkins', position: 'WR', team: 'TEN', rank: 203, byeWeek: 5),
    Player(id: 'wr52', name: 'Elijah Moore', position: 'WR', team: 'CLE', rank: 207, byeWeek: 10),
    Player(id: 'wr53', name: 'Allen Lazard', position: 'WR', team: 'NYJ', rank: 211, byeWeek: 12),
    Player(id: 'wr54', name: 'Tyler Boyd', position: 'WR', team: 'TEN', rank: 216, byeWeek: 5),
    Player(id: 'wr55', name: 'Gabe Davis', position: 'WR', team: 'JAX', rank: 220, byeWeek: 12),
    Player(id: 'wr56', name: 'Christian Watson', position: 'WR', team: 'GB', rank: 224, byeWeek: 10),
    Player(id: 'wr57', name: 'Romeo Doubs', position: 'WR', team: 'GB', rank: 228, byeWeek: 10),
    Player(id: 'wr58', name: 'Marquise Brown', position: 'WR', team: 'KC', rank: 233, byeWeek: 6),
    Player(id: 'wr59', name: 'Chris Godwin', position: 'WR', team: 'TB', rank: 237, byeWeek: 11),
    Player(id: 'wr60', name: 'Treylon Burks', position: 'WR', team: 'TEN', rank: 242, byeWeek: 5),
    Player(id: 'wr61', name: 'Kadarius Toney', position: 'WR', team: 'KC', rank: 247, byeWeek: 6),
    Player(id: 'wr62', name: 'Demarcus Robinson', position: 'WR', team: 'LAR', rank: 252, byeWeek: 6),
    Player(id: 'wr63', name: 'Dontayvion Wicks', position: 'WR', team: 'GB', rank: 256, byeWeek: 10),
    Player(id: 'wr64', name: 'Jayden Reed', position: 'WR', team: 'GB', rank: 260, byeWeek: 10),
    Player(id: 'wr65', name: 'Adonai Mitchell', position: 'WR', team: 'IND', rank: 264, byeWeek: 14),
    Player(id: 'wr66', name: 'Brian Thomas Jr.', position: 'WR', team: 'JAX', rank: 268, byeWeek: 12),
    Player(id: 'wr67', name: 'Rashid Shaheed', position: 'WR', team: 'NO', rank: 273, byeWeek: 12),
    Player(id: 'wr68', name: 'Jalen Tolbert', position: 'WR', team: 'DAL', rank: 278, byeWeek: 7),
    Player(id: 'wr69', name: 'Demario Douglas', position: 'WR', team: 'NE', rank: 283, byeWeek: 14),
    Player(id: 'wr70', name: 'Skyy Moore', position: 'WR', team: 'KC', rank: 288, byeWeek: 6),
    Player(id: 'wr71', name: 'Cedric Tillman', position: 'WR', team: 'CLE', rank: 293, byeWeek: 10),
    Player(id: 'wr72', name: 'Jalin Hyatt', position: 'WR', team: 'NYG', rank: 298, byeWeek: 11),
    Player(id: 'wr73', name: 'Marvin Jones Jr.', position: 'WR', team: 'DET', rank: 303, byeWeek: 5),
    Player(id: 'wr74', name: 'DeVante Parker', position: 'WR', team: 'NE', rank: 308, byeWeek: 14),
    Player(id: 'wr75', name: 'Mecole Hardman', position: 'WR', team: 'KC', rank: 313, byeWeek: 6),
    Player(id: 'wr76', name: 'Terrace Marshall Jr.', position: 'WR', team: 'CAR', rank: 318, byeWeek: 11),
    Player(id: 'wr77', name: 'Rondale Moore', position: 'WR', team: 'ARI', rank: 323, byeWeek: 11),
    Player(id: 'wr78', name: 'Quez Watkins', position: 'WR', team: 'PHI', rank: 328, byeWeek: 14),
    Player(id: 'wr79', name: 'Parris Campbell', position: 'WR', team: 'NYG', rank: 333, byeWeek: 11),
    Player(id: 'wr80', name: 'Tyquan Thornton', position: 'WR', team: 'NE', rank: 338, byeWeek: 14),
    Player(id: 'wr81', name: 'Tutu Atwell', position: 'WR', team: 'LAR', rank: 343, byeWeek: 6),
    Player(id: 'wr82', name: 'Velus Jones Jr.', position: 'WR', team: 'CHI', rank: 348, byeWeek: 7),
    Player(id: 'wr83', name: 'Donovan Peoples-Jones', position: 'WR', team: 'DET', rank: 353, byeWeek: 5),
    Player(id: 'wr84', name: 'Derius Davis', position: 'WR', team: 'LAC', rank: 358, byeWeek: 5),
    Player(id: 'wr85', name: 'Joshua Palmer', position: 'WR', team: 'LAC', rank: 363, byeWeek: 5),
    Player(id: 'wr86', name: 'Jahan Dotson', position: 'WR', team: 'WAS', rank: 368, byeWeek: 14),
    Player(id: 'wr87', name: 'Tim Patrick', position: 'WR', team: 'DEN', rank: 373, byeWeek: 14),
    Player(id: 'wr88', name: 'Van Jefferson', position: 'WR', team: 'PIT', rank: 378, byeWeek: 9),
    Player(id: 'wr89', name: 'Noah Brown', position: 'WR', team: 'HOU', rank: 383, byeWeek: 14),
    Player(id: 'wr90', name: 'Kendrick Bourne', position: 'WR', team: 'NE', rank: 388, byeWeek: 14),
    Player(id: 'wr91', name: 'Ray-Ray McCloud', position: 'WR', team: 'ATL', rank: 393, byeWeek: 12),
    Player(id: 'wr92', name: 'Zay Jones', position: 'WR', team: 'ARI', rank: 398, byeWeek: 11),
    Player(id: 'wr93', name: 'Marquez Valdes-Scantling', position: 'WR', team: 'BUF', rank: 403, byeWeek: 12),
    Player(id: 'wr94', name: 'Sterling Shepard', position: 'WR', team: 'TB', rank: 408, byeWeek: 11),
    Player(id: 'wr95', name: 'Laquon Treadwell', position: 'WR', team: 'JAX', rank: 413, byeWeek: 12),
    Player(id: 'wr96', name: 'Shi Smith', position: 'WR', team: 'CAR', rank: 418, byeWeek: 11),
    Player(id: 'wr97', name: 'Equanimeous St. Brown', position: 'WR', team: 'NO', rank: 423, byeWeek: 12),
    Player(id: 'wr98', name: 'Dyami Brown', position: 'WR', team: 'WAS', rank: 428, byeWeek: 14),
    Player(id: 'wr99', name: 'Byron Pringle', position: 'WR', team: 'CIN', rank: 433, byeWeek: 12),
    Player(id: 'wr100', name: 'Kalif Raymond', position: 'WR', team: 'DET', rank: 438, byeWeek: 5),
    Player(id: 'wr101', name: 'Mack Hollins', position: 'WR', team: 'BUF', rank: 439, byeWeek: 12),
    Player(id: 'wr102', name: 'KJ Osborn', position: 'WR', team: 'NE', rank: 440, byeWeek: 14),
    Player(id: 'wr103', name: 'Richie James', position: 'WR', team: 'JAX', rank: 441, byeWeek: 12),
    Player(id: 'wr104', name: 'Russell Gage', position: 'WR', team: 'TB', rank: 442, byeWeek: 11),
    Player(id: 'wr105', name: 'Corey Davis', position: 'WR', team: 'NYJ', rank: 443, byeWeek: 12),
    Player(id: 'wr106', name: 'Tre\'Quan Smith', position: 'WR', team: 'NO', rank: 444, byeWeek: 12),
    Player(id: 'wr107', name: 'A.T. Perry', position: 'WR', team: 'NO', rank: 445, byeWeek: 12),
    Player(id: 'wr108', name: 'Trent Sherfield', position: 'WR', team: 'MIN', rank: 446, byeWeek: 6),
    Player(id: 'wr109', name: 'David Bell', position: 'WR', team: 'CLE', rank: 447, byeWeek: 10),
    Player(id: 'wr110', name: 'Mecole Hardman Jr.', position: 'WR', team: 'KC', rank: 448, byeWeek: 6),
    Player(id: 'wr111', name: 'Laviska Shenault', position: 'WR', team: 'SEA', rank: 449, byeWeek: 10),
    Player(id: 'wr112', name: 'Ben Skowronek', position: 'WR', team: 'LAR', rank: 450, byeWeek: 6),
    Player(id: 'wr113', name: 'Olamide Zaccheaus', position: 'WR', team: 'PHI', rank: 451, byeWeek: 14),
    Player(id: 'wr114', name: 'Colton Dowell', position: 'WR', team: 'TEN', rank: 452, byeWeek: 5),
    Player(id: 'wr115', name: 'Denzel Mims', position: 'WR', team: 'JAX', rank: 453, byeWeek: 12),
    Player(id: 'wr116', name: 'Simi Fehoko', position: 'WR', team: 'DAL', rank: 454, byeWeek: 7),
    Player(id: 'wr117', name: 'Marquez Callaway', position: 'WR', team: 'TEN', rank: 455, byeWeek: 5),
    Player(id: 'wr118', name: 'Phillip Dorsett', position: 'WR', team: 'HOU', rank: 456, byeWeek: 14),
    Player(id: 'wr119', name: 'Chris Moore', position: 'WR', team: 'CLE', rank: 457, byeWeek: 10),
    Player(id: 'wr120', name: 'Tylan Wallace', position: 'WR', team: 'BAL', rank: 458, byeWeek: 14),
    Player(id: 'wr121', name: 'Justyn Ross', position: 'WR', team: 'KC', rank: 459, byeWeek: 6),
    Player(id: 'wr122', name: 'Lil\'Jordan Humphrey', position: 'WR', team: 'DEN', rank: 460, byeWeek: 14),
    Player(id: 'wr123', name: 'Bo Melton', position: 'WR', team: 'GB', rank: 461, byeWeek: 10),
    Player(id: 'wr124', name: 'Greg Dortch', position: 'WR', team: 'ARI', rank: 462, byeWeek: 11),
    Player(id: 'wr125', name: 'Ihmir Smith-Marsette', position: 'WR', team: 'CHI', rank: 463, byeWeek: 7),
    Player(id: 'wr126', name: 'Deven Thompkins', position: 'WR', team: 'TB', rank: 464, byeWeek: 11),
    Player(id: 'wr127', name: 'Nelson Agholor', position: 'WR', team: 'BAL', rank: 465, byeWeek: 14),
    Player(id: 'wr128', name: 'Jamal Agnew', position: 'WR', team: 'JAX', rank: 466, byeWeek: 12),
    Player(id: 'wr129', name: 'KJ Hamler', position: 'WR', team: 'DEN', rank: 467, byeWeek: 14),
    Player(id: 'wr130', name: 'Kadarius Toney II', position: 'WR', team: 'CLE', rank: 468, byeWeek: 10),
    Player(id: 'wr131', name: 'Jauan Jennings', position: 'WR', team: 'SF', rank: 469, byeWeek: 9),
    Player(id: 'wr132', name: 'Devin Duvernay', position: 'WR', team: 'BAL', rank: 470, byeWeek: 14),
    Player(id: 'wr133', name: 'Isaiah McKenzie', position: 'WR', team: 'IND', rank: 471, byeWeek: 14),
    Player(id: 'wr134', name: 'Trey Palmer', position: 'WR', team: 'TB', rank: 472, byeWeek: 11),
    Player(id: 'wr135', name: 'Scotty Miller', position: 'WR', team: 'ATL', rank: 473, byeWeek: 12),
    Player(id: 'wr136', name: 'Michael Wilson', position: 'WR', team: 'ARI', rank: 474, byeWeek: 11),
    Player(id: 'wr137', name: 'DJ Chark', position: 'WR', team: 'LAC', rank: 475, byeWeek: 5),
    Player(id: 'wr138', name: 'Amari Rodgers', position: 'WR', team: 'NO', rank: 476, byeWeek: 12),
    Player(id: 'wr139', name: 'Alec Pierce', position: 'WR', team: 'IND', rank: 477, byeWeek: 14),
    Player(id: 'wr140', name: 'John Metchie III', position: 'WR', team: 'HOU', rank: 478, byeWeek: 14),
    Player(id: 'wr141', name: 'Jalen Nailor', position: 'WR', team: 'MIN', rank: 479, byeWeek: 6),
    Player(id: 'wr142', name: 'Jarvis Landry', position: 'WR', team: 'NO', rank: 480, byeWeek: 12),
    Player(id: 'wr143', name: 'Tyrie Cleveland', position: 'WR', team: 'DEN', rank: 481, byeWeek: 14),
    Player(id: 'wr144', name: 'Darius Slayton', position: 'WR', team: 'NYG', rank: 482, byeWeek: 11),
    Player(id: 'wr145', name: 'Kendall Wright', position: 'WR', team: 'WAS', rank: 483, byeWeek: 14),
    Player(id: 'wr146', name: 'Allen Robinson', position: 'WR', team: 'DET', rank: 484, byeWeek: 5),
    Player(id: 'wr147', name: 'Jamison Crowder', position: 'WR', team: 'WAS', rank: 485, byeWeek: 14),
    Player(id: 'wr148', name: 'Randall Cobb', position: 'WR', team: 'NYJ', rank: 486, byeWeek: 12),
    Player(id: 'wr149', name: 'Marquez Stevenson', position: 'WR', team: 'PIT', rank: 487, byeWeek: 9),
    Player(id: 'wr150', name: 'Anthony Schwartz', position: 'WR', team: 'CLE', rank: 488, byeWeek: 10),
    // ─── Tight Ends (40) ─────────────────────────────────────────────
    Player(id: 'te1', name: 'Travis Kelce', position: 'TE', team: 'KC', rank: 5, byeWeek: 6),
    Player(id: 'te2', name: 'Sam LaPorta', position: 'TE', team: 'DET', rank: 24, byeWeek: 5),
    Player(id: 'te3', name: 'Mark Andrews', position: 'TE', team: 'BAL', rank: 32, byeWeek: 14),
    Player(id: 'te4', name: 'T.J. Hockenson', position: 'TE', team: 'MIN', rank: 46, byeWeek: 6),
    Player(id: 'te5', name: 'George Kittle', position: 'TE', team: 'SF', rank: 53, byeWeek: 9),
    Player(id: 'te6', name: 'Dallas Goedert', position: 'TE', team: 'PHI', rank: 65, byeWeek: 14),
    Player(id: 'te7', name: 'Evan Engram', position: 'TE', team: 'JAX', rank: 77, byeWeek: 12),
    Player(id: 'te8', name: 'David Njoku', position: 'TE', team: 'CLE', rank: 86, byeWeek: 10),
    Player(id: 'te9', name: 'Dalton Kincaid', position: 'TE', team: 'BUF', rank: 94, byeWeek: 12),
    Player(id: 'te10', name: 'Kyle Pitts', position: 'TE', team: 'ATL', rank: 103, byeWeek: 12),
    Player(id: 'te11', name: 'Jake Ferguson', position: 'TE', team: 'DAL', rank: 109, byeWeek: 7),
    Player(id: 'te12', name: 'Pat Freiermuth', position: 'TE', team: 'PIT', rank: 116, byeWeek: 9),
    Player(id: 'te13', name: 'Trey McBride', position: 'TE', team: 'ARI', rank: 124, byeWeek: 11),
    Player(id: 'te14', name: 'Cole Kmet', position: 'TE', team: 'CHI', rank: 133, byeWeek: 7),
    Player(id: 'te15', name: 'Brock Bowers', position: 'TE', team: 'LV', rank: 139, byeWeek: 10),
    Player(id: 'te16', name: 'Michael Mayer', position: 'TE', team: 'LV', rank: 150, byeWeek: 10),
    Player(id: 'te17', name: 'Jonnu Smith', position: 'TE', team: 'MIA', rank: 160, byeWeek: 6),
    Player(id: 'te18', name: 'Cade Otton', position: 'TE', team: 'TB', rank: 175, byeWeek: 11),
    Player(id: 'te19', name: 'Chigoziem Okonkwo', position: 'TE', team: 'TEN', rank: 189, byeWeek: 5),
    Player(id: 'te20', name: 'Luke Musgrave', position: 'TE', team: 'GB', rank: 202, byeWeek: 10),
    Player(id: 'te21', name: 'Juwan Johnson', position: 'TE', team: 'NO', rank: 213, byeWeek: 12),
    Player(id: 'te22', name: 'Mike Gesicki', position: 'TE', team: 'CIN', rank: 222, byeWeek: 12),
    Player(id: 'te23', name: 'Greg Dulcich', position: 'TE', team: 'DEN', rank: 235, byeWeek: 14),
    Player(id: 'te24', name: 'Hunter Henry', position: 'TE', team: 'NE', rank: 248, byeWeek: 14),
    Player(id: 'te25', name: 'Dawson Knox', position: 'TE', team: 'BUF', rank: 262, byeWeek: 12),
    Player(id: 'te26', name: 'Tyler Conklin', position: 'TE', team: 'NYJ', rank: 275, byeWeek: 12),
    Player(id: 'te27', name: 'Noah Fant', position: 'TE', team: 'SEA', rank: 290, byeWeek: 10),
    Player(id: 'te28', name: 'Austin Hooper', position: 'TE', team: 'NE', rank: 305, byeWeek: 14),
    Player(id: 'te29', name: 'Hayden Hurst', position: 'TE', team: 'LAC', rank: 315, byeWeek: 5),
    Player(id: 'te30', name: 'Durham Smythe', position: 'TE', team: 'MIA', rank: 330, byeWeek: 6),
    Player(id: 'te31', name: 'Logan Thomas', position: 'TE', team: 'WAS', rank: 345, byeWeek: 14),
    Player(id: 'te32', name: 'Jelani Woods', position: 'TE', team: 'IND', rank: 358, byeWeek: 14),
    Player(id: 'te33', name: 'Isaiah Likely', position: 'TE', team: 'BAL', rank: 365, byeWeek: 14),
    Player(id: 'te34', name: 'Tucker Kraft', position: 'TE', team: 'GB', rank: 375, byeWeek: 10),
    Player(id: 'te35', name: 'Theo Johnson', position: 'TE', team: 'NYG', rank: 390, byeWeek: 11),
    Player(id: 'te36', name: 'Taysom Hill', position: 'TE', team: 'NO', rank: 405, byeWeek: 12),
    Player(id: 'te37', name: 'Zach Ertz', position: 'TE', team: 'WAS', rank: 420, byeWeek: 14),
    Player(id: 'te38', name: 'Gerald Everett', position: 'TE', team: 'CHI', rank: 435, byeWeek: 7),
    Player(id: 'te39', name: 'Irv Smith Jr.', position: 'TE', team: 'CIN', rank: 445, byeWeek: 12),
    Player(id: 'te40', name: 'Foster Moreau', position: 'TE', team: 'NO', rank: 458, byeWeek: 12),
    // ─── Kickers (32) ────────────────────────────────────────────────
    Player(id: 'k1', name: 'Justin Tucker', position: 'K', team: 'BAL', rank: 440, byeWeek: 14),
    Player(id: 'k2', name: 'Harrison Butker', position: 'K', team: 'KC', rank: 441, byeWeek: 6),
    Player(id: 'k3', name: 'Jake Elliott', position: 'K', team: 'PHI', rank: 442, byeWeek: 14),
    Player(id: 'k4', name: 'Tyler Bass', position: 'K', team: 'BUF', rank: 443, byeWeek: 12),
    Player(id: 'k5', name: 'Evan McPherson', position: 'K', team: 'CIN', rank: 444, byeWeek: 12),
    Player(id: 'k6', name: 'Ka\'imi Fairbairn', position: 'K', team: 'HOU', rank: 445, byeWeek: 14),
    Player(id: 'k7', name: 'Brandon Aubrey', position: 'K', team: 'DAL', rank: 446, byeWeek: 7),
    Player(id: 'k8', name: 'Jason Sanders', position: 'K', team: 'MIA', rank: 447, byeWeek: 6),
    Player(id: 'k9', name: 'Cameron Dicker', position: 'K', team: 'LAC', rank: 448, byeWeek: 5),
    Player(id: 'k10', name: 'Matt Gay', position: 'K', team: 'IND', rank: 449, byeWeek: 14),
    Player(id: 'k11', name: 'Younghoe Koo', position: 'K', team: 'ATL', rank: 450, byeWeek: 12),
    Player(id: 'k12', name: 'Daniel Carlson', position: 'K', team: 'LV', rank: 451, byeWeek: 10),
    Player(id: 'k13', name: 'Jake Moody', position: 'K', team: 'SF', rank: 452, byeWeek: 9),
    Player(id: 'k14', name: 'Jason Myers', position: 'K', team: 'SEA', rank: 453, byeWeek: 10),
    Player(id: 'k15', name: 'Greg Zuerlein', position: 'K', team: 'NYJ', rank: 454, byeWeek: 12),
    Player(id: 'k16', name: 'Chris Boswell', position: 'K', team: 'PIT', rank: 455, byeWeek: 9),
    Player(id: 'k17', name: 'Matt Prater', position: 'K', team: 'ARI', rank: 456, byeWeek: 11),
    Player(id: 'k18', name: 'Chase McLaughlin', position: 'K', team: 'TB', rank: 457, byeWeek: 11),
    Player(id: 'k19', name: 'Dustin Hopkins', position: 'K', team: 'CLE', rank: 458, byeWeek: 10),
    Player(id: 'k20', name: 'Graham Gano', position: 'K', team: 'NYG', rank: 459, byeWeek: 11),
    Player(id: 'k21', name: 'Riley Patterson', position: 'K', team: 'JAX', rank: 460, byeWeek: 12),
    Player(id: 'k22', name: 'Blake Grupe', position: 'K', team: 'NO', rank: 461, byeWeek: 12),
    Player(id: 'k23', name: 'Cairo Santos', position: 'K', team: 'CHI', rank: 462, byeWeek: 7),
    Player(id: 'k24', name: 'Nick Folk', position: 'K', team: 'TEN', rank: 463, byeWeek: 5),
    Player(id: 'k25', name: 'Anders Carlson', position: 'K', team: 'GB', rank: 464, byeWeek: 10),
    Player(id: 'k26', name: 'Eddy Pineiro', position: 'K', team: 'CAR', rank: 465, byeWeek: 11),
    Player(id: 'k27', name: 'Wil Lutz', position: 'K', team: 'DEN', rank: 466, byeWeek: 14),
    Player(id: 'k28', name: 'Joey Slye', position: 'K', team: 'WAS', rank: 467, byeWeek: 14),
    Player(id: 'k29', name: 'Chad Ryland', position: 'K', team: 'NE', rank: 468, byeWeek: 14),
    Player(id: 'k30', name: 'Brett Maher', position: 'K', team: 'LAR', rank: 469, byeWeek: 6),
    Player(id: 'k31', name: 'Michael Badgley', position: 'K', team: 'DET', rank: 470, byeWeek: 5),
    Player(id: 'k32', name: 'Cade York', position: 'K', team: 'MIN', rank: 471, byeWeek: 6),
    // ─── Team Defense (32) ─────────────────────────────────────────
    Player(id: 'def1', name: 'San Francisco 49ers', position: 'DEF', team: 'SF', rank: 472, byeWeek: 9),
    Player(id: 'def2', name: 'Dallas Cowboys', position: 'DEF', team: 'DAL', rank: 473, byeWeek: 7),
    Player(id: 'def3', name: 'Baltimore Ravens', position: 'DEF', team: 'BAL', rank: 474, byeWeek: 14),
    Player(id: 'def4', name: 'New York Jets', position: 'DEF', team: 'NYJ', rank: 475, byeWeek: 12),
    Player(id: 'def5', name: 'Cleveland Browns', position: 'DEF', team: 'CLE', rank: 476, byeWeek: 10),
    Player(id: 'def6', name: 'Buffalo Bills', position: 'DEF', team: 'BUF', rank: 477, byeWeek: 12),
    Player(id: 'def7', name: 'Pittsburgh Steelers', position: 'DEF', team: 'PIT', rank: 478, byeWeek: 9),
    Player(id: 'def8', name: 'Kansas City Chiefs', position: 'DEF', team: 'KC', rank: 479, byeWeek: 6),
    Player(id: 'def9', name: 'Miami Dolphins', position: 'DEF', team: 'MIA', rank: 480, byeWeek: 6),
    Player(id: 'def10', name: 'Houston Texans', position: 'DEF', team: 'HOU', rank: 481, byeWeek: 14),
    Player(id: 'def11', name: 'Detroit Lions', position: 'DEF', team: 'DET', rank: 482, byeWeek: 5),
    Player(id: 'def12', name: 'Philadelphia Eagles', position: 'DEF', team: 'PHI', rank: 483, byeWeek: 14),
    Player(id: 'def13', name: 'Minnesota Vikings', position: 'DEF', team: 'MIN', rank: 484, byeWeek: 6),
    Player(id: 'def14', name: 'New Orleans Saints', position: 'DEF', team: 'NO', rank: 485, byeWeek: 12),
    Player(id: 'def15', name: 'Denver Broncos', position: 'DEF', team: 'DEN', rank: 486, byeWeek: 14),
    Player(id: 'def16', name: 'Cincinnati Bengals', position: 'DEF', team: 'CIN', rank: 487, byeWeek: 12),
    Player(id: 'def17', name: 'Seattle Seahawks', position: 'DEF', team: 'SEA', rank: 488, byeWeek: 10),
    Player(id: 'def18', name: 'Green Bay Packers', position: 'DEF', team: 'GB', rank: 489, byeWeek: 10),
    Player(id: 'def19', name: 'Tampa Bay Buccaneers', position: 'DEF', team: 'TB', rank: 490, byeWeek: 11),
    Player(id: 'def20', name: 'Indianapolis Colts', position: 'DEF', team: 'IND', rank: 491, byeWeek: 14),
    Player(id: 'def21', name: 'Los Angeles Chargers', position: 'DEF', team: 'LAC', rank: 492, byeWeek: 5),
    Player(id: 'def22', name: 'New England Patriots', position: 'DEF', team: 'NE', rank: 493, byeWeek: 14),
    Player(id: 'def23', name: 'Chicago Bears', position: 'DEF', team: 'CHI', rank: 494, byeWeek: 7),
    Player(id: 'def24', name: 'Jacksonville Jaguars', position: 'DEF', team: 'JAX', rank: 495, byeWeek: 12),
    Player(id: 'def25', name: 'Atlanta Falcons', position: 'DEF', team: 'ATL', rank: 496, byeWeek: 12),
    Player(id: 'def26', name: 'Los Angeles Rams', position: 'DEF', team: 'LAR', rank: 497, byeWeek: 6),
    Player(id: 'def27', name: 'Las Vegas Raiders', position: 'DEF', team: 'LV', rank: 498, byeWeek: 10),
    Player(id: 'def28', name: 'Washington Commanders', position: 'DEF', team: 'WAS', rank: 499, byeWeek: 14),
    Player(id: 'def29', name: 'Tennessee Titans', position: 'DEF', team: 'TEN', rank: 500, byeWeek: 5),
    Player(id: 'def30', name: 'Carolina Panthers', position: 'DEF', team: 'CAR', rank: 501, byeWeek: 11),
    Player(id: 'def31', name: 'New York Giants', position: 'DEF', team: 'NYG', rank: 502, byeWeek: 11),
    Player(id: 'def32', name: 'Arizona Cardinals', position: 'DEF', team: 'ARI', rank: 503, byeWeek: 11),
    // ─── Extra Depth RBs (34) ──────────────────────────────────────
    Player(id: 'rb81', name: 'Melvin Gordon', position: 'RB', team: 'SD', rank: 504, byeWeek: 5),
    Player(id: 'rb82', name: 'J.K. Dobbins', position: 'RB', team: 'LAC', rank: 505, byeWeek: 5),
    Player(id: 'rb83', name: 'Damien Harris', position: 'RB', team: 'BUF', rank: 506, byeWeek: 12),
    Player(id: 'rb84', name: 'Latavius Murray', position: 'RB', team: 'BUF', rank: 507, byeWeek: 12),
    Player(id: 'rb85', name: 'Boston Scott', position: 'RB', team: 'PHI', rank: 508, byeWeek: 14),
    Player(id: 'rb86', name: 'Nyheim Hines', position: 'RB', team: 'BUF', rank: 509, byeWeek: 12),
    Player(id: 'rb87', name: 'Devontae Booker', position: 'RB', team: 'LV', rank: 510, byeWeek: 10),
    Player(id: 'rb88', name: 'Jalen Richard', position: 'RB', team: 'LV', rank: 511, byeWeek: 10),
    Player(id: 'rb89', name: 'Mike Boone', position: 'RB', team: 'HOU', rank: 512, byeWeek: 14),
    Player(id: 'rb90', name: 'Mark Ingram', position: 'RB', team: 'HOU', rank: 513, byeWeek: 14),
    Player(id: 'rb91', name: 'Ameer Abdullah', position: 'RB', team: 'LV', rank: 514, byeWeek: 10),
    Player(id: 'rb92', name: 'Damien Williams', position: 'RB', team: 'ATL', rank: 515, byeWeek: 12),
    Player(id: 'rb93', name: 'Rex Burkhead', position: 'RB', team: 'HOU', rank: 516, byeWeek: 14),
    Player(id: 'rb94', name: 'Craig Reynolds', position: 'RB', team: 'DET', rank: 517, byeWeek: 5),
    Player(id: 'rb95', name: 'Matt Breida', position: 'RB', team: 'NYG', rank: 518, byeWeek: 11),
    Player(id: 'rb96', name: 'Tyrion Davis-Price', position: 'RB', team: 'SF', rank: 519, byeWeek: 9),
    Player(id: 'rb97', name: 'Snoop Conner', position: 'RB', team: 'JAX', rank: 520, byeWeek: 12),
    Player(id: 'rb98', name: 'Mike Davis', position: 'RB', team: 'CAR', rank: 521, byeWeek: 11),
    Player(id: 'rb99', name: 'Sony Michel', position: 'RB', team: 'ATL', rank: 522, byeWeek: 12),
    Player(id: 'rb100', name: 'Ke\'Shawn Vaughn', position: 'RB', team: 'TB', rank: 523, byeWeek: 11),
    Player(id: 'rb101', name: 'Caleb Huntley', position: 'RB', team: 'ATL', rank: 524, byeWeek: 12),
    Player(id: 'rb102', name: 'Dontrell Hilliard', position: 'RB', team: 'TEN', rank: 525, byeWeek: 5),
    Player(id: 'rb103', name: 'Eno Benjamin', position: 'RB', team: 'HOU', rank: 526, byeWeek: 14),
    Player(id: 'rb104', name: 'Dare Ogunbowale', position: 'RB', team: 'JAX', rank: 527, byeWeek: 12),
    Player(id: 'rb105', name: 'Derrick Gore', position: 'RB', team: 'BUF', rank: 528, byeWeek: 12),
    Player(id: 'rb106', name: 'Larry Rountree', position: 'RB', team: 'LAC', rank: 529, byeWeek: 5),
    Player(id: 'rb107', name: 'Deon Jackson', position: 'RB', team: 'IND', rank: 530, byeWeek: 14),
    Player(id: 'rb108', name: 'Isaiah Spiller', position: 'RB', team: 'LAC', rank: 531, byeWeek: 5),
    Player(id: 'rb109', name: 'Tyler Badie', position: 'RB', team: 'BAL', rank: 532, byeWeek: 14),
    Player(id: 'rb110', name: 'Kylin Hill', position: 'RB', team: 'GB', rank: 533, byeWeek: 10),
    Player(id: 'rb111', name: 'Darrel Williams', position: 'RB', team: 'ARI', rank: 534, byeWeek: 11),
    Player(id: 'rb112', name: 'Phillip Lindsay', position: 'RB', team: 'IND', rank: 535, byeWeek: 14),
    Player(id: 'rb113', name: 'Gary Brightwell', position: 'RB', team: 'NYG', rank: 536, byeWeek: 11),
    Player(id: 'rb114', name: 'Jamaal Williams', position: 'RB', team: 'NO', rank: 537, byeWeek: 12),
    // ─── Extra Depth WRs (50) ──────────────────────────────────────
    Player(id: 'wr151', name: 'Tarik Black', position: 'WR', team: 'NYG', rank: 538, byeWeek: 11),
    Player(id: 'wr152', name: 'Chris Conley', position: 'WR', team: 'HOU', rank: 539, byeWeek: 14),
    Player(id: 'wr153', name: 'D.J. Chark Jr.', position: 'WR', team: 'LAC', rank: 540, byeWeek: 5),
    Player(id: 'wr154', name: 'Sammy Watkins', position: 'WR', team: 'GB', rank: 541, byeWeek: 10),
    Player(id: 'wr155', name: 'DeSean Jackson', position: 'WR', team: 'BAL', rank: 542, byeWeek: 14),
    Player(id: 'wr156', name: 'Robert Woods', position: 'WR', team: 'HOU', rank: 543, byeWeek: 14),
    Player(id: 'wr157', name: 'Jarvis Landry Jr.', position: 'WR', team: 'NO', rank: 544, byeWeek: 12),
    Player(id: 'wr158', name: 'Laquon Treadwell Jr.', position: 'WR', team: 'SEA', rank: 545, byeWeek: 10),
    Player(id: 'wr159', name: 'Hunter Renfrow', position: 'WR', team: 'LV', rank: 546, byeWeek: 10),
    Player(id: 'wr160', name: 'Will Fuller', position: 'WR', team: 'MIA', rank: 547, byeWeek: 6),
    Player(id: 'wr161', name: 'Emmanuel Sanders', position: 'WR', team: 'BUF', rank: 548, byeWeek: 12),
    Player(id: 'wr162', name: 'Kenny Golladay', position: 'WR', team: 'NYG', rank: 549, byeWeek: 11),
    Player(id: 'wr163', name: 'Chester Rogers', position: 'WR', team: 'TEN', rank: 550, byeWeek: 5),
    Player(id: 'wr164', name: 'Tajae Sharpe', position: 'WR', team: 'ATL', rank: 551, byeWeek: 12),
    Player(id: 'wr165', name: 'Andy Isabella', position: 'WR', team: 'ARI', rank: 552, byeWeek: 11),
    Player(id: 'wr166', name: 'Freddie Swain', position: 'WR', team: 'SEA', rank: 553, byeWeek: 10),
    Player(id: 'wr167', name: 'Quintez Cephus', position: 'WR', team: 'DET', rank: 554, byeWeek: 5),
    Player(id: 'wr168', name: 'Randall Cobb Jr.', position: 'WR', team: 'DAL', rank: 555, byeWeek: 7),
    Player(id: 'wr169', name: 'Dante Pettis', position: 'WR', team: 'CHI', rank: 556, byeWeek: 7),
    Player(id: 'wr170', name: 'Kelvin Harmon', position: 'WR', team: 'WAS', rank: 557, byeWeek: 14),
    Player(id: 'wr171', name: 'N\'Keal Harry', position: 'WR', team: 'CHI', rank: 558, byeWeek: 7),
    Player(id: 'wr172', name: 'Breshad Perriman', position: 'WR', team: 'TB', rank: 559, byeWeek: 11),
    Player(id: 'wr173', name: 'Phillip Dorsett II', position: 'WR', team: 'IND', rank: 560, byeWeek: 14),
    Player(id: 'wr174', name: 'Braxton Berrios', position: 'WR', team: 'MIA', rank: 561, byeWeek: 6),
    Player(id: 'wr175', name: 'Jalen Reagor', position: 'WR', team: 'NE', rank: 562, byeWeek: 14),
    Player(id: 'wr176', name: 'Dax Milne', position: 'WR', team: 'WAS', rank: 563, byeWeek: 14),
    Player(id: 'wr177', name: 'Limas Sweed', position: 'WR', team: 'PIT', rank: 564, byeWeek: 9),
    Player(id: 'wr178', name: 'Terrace Marshall Jr.', position: 'WR', team: 'CAR', rank: 565, byeWeek: 11),
    Player(id: 'wr179', name: 'Amon-Ra Anderson', position: 'WR', team: 'CIN', rank: 566, byeWeek: 12),
    Player(id: 'wr180', name: 'Javon Wims', position: 'WR', team: 'NYG', rank: 567, byeWeek: 11),
    Player(id: 'wr181', name: 'Travis Fulgham', position: 'WR', team: 'PHI', rank: 568, byeWeek: 14),
    Player(id: 'wr182', name: 'Cam Sims', position: 'WR', team: 'WAS', rank: 569, byeWeek: 14),
    Player(id: 'wr183', name: 'Jalen Virgil', position: 'WR', team: 'DEN', rank: 570, byeWeek: 14),
    Player(id: 'wr184', name: 'Kyle Philips', position: 'WR', team: 'TEN', rank: 571, byeWeek: 5),
    // ─── Extra Depth TEs (16) ──────────────────────────────────────
    Player(id: 'te41', name: 'OJ Howard', position: 'TE', team: 'HOU', rank: 572, byeWeek: 14),
    Player(id: 'te42', name: 'Robert Tonyan', position: 'TE', team: 'MIN', rank: 573, byeWeek: 6),
    Player(id: 'te43', name: 'Dan Arnold', position: 'TE', team: 'JAX', rank: 574, byeWeek: 12),
    Player(id: 'te44', name: 'Adam Trautman', position: 'TE', team: 'NO', rank: 575, byeWeek: 12),
    Player(id: 'te45', name: 'Brevin Jordan', position: 'TE', team: 'HOU', rank: 576, byeWeek: 14),
    Player(id: 'te46', name: 'Harrison Bryant', position: 'TE', team: 'CLE', rank: 577, byeWeek: 10),
    Player(id: 'te47', name: 'Albert Okwuegbunam', position: 'TE', team: 'DEN', rank: 578, byeWeek: 14),
    Player(id: 'te48', name: 'Josh Oliver', position: 'TE', team: 'MIN', rank: 579, byeWeek: 6),
    Player(id: 'te49', name: 'Tommy Tremble', position: 'TE', team: 'CAR', rank: 580, byeWeek: 11),
    Player(id: 'te50', name: 'Cameron Brate', position: 'TE', team: 'TB', rank: 581, byeWeek: 11),
    Player(id: 'te51', name: 'Geoff Swaim', position: 'TE', team: 'TEN', rank: 582, byeWeek: 5),
    Player(id: 'te52', name: 'Donald Parham', position: 'TE', team: 'LAC', rank: 583, byeWeek: 5),
    Player(id: 'te53', name: 'Will Dissly', position: 'TE', team: 'LAC', rank: 584, byeWeek: 5),
    Player(id: 'te54', name: 'Daniel Bellinger', position: 'TE', team: 'NYG', rank: 585, byeWeek: 11),
    Player(id: 'te55', name: 'Kylen Granson', position: 'TE', team: 'IND', rank: 586, byeWeek: 14),
    Player(id: 'te56', name: 'Peyton Hendershot', position: 'TE', team: 'DAL', rank: 587, byeWeek: 7),
    // ─── Final Depth (50) ──────────────────────────────────────────
    Player(id: 'rb115', name: 'Ke\'Shawn Williams', position: 'RB', team: 'NYJ', rank: 588, byeWeek: 12),
    Player(id: 'rb116', name: 'Patrick Laird', position: 'RB', team: 'MIA', rank: 589, byeWeek: 6),
    Player(id: 'rb117', name: 'Salvon Ahmed', position: 'RB', team: 'MIA', rank: 590, byeWeek: 6),
    Player(id: 'rb118', name: 'Darrynton Evans', position: 'RB', team: 'CHI', rank: 591, byeWeek: 7),
    Player(id: 'rb119', name: 'Chris Evans', position: 'RB', team: 'CIN', rank: 592, byeWeek: 12),
    Player(id: 'rb120', name: 'Darius Bradwell', position: 'RB', team: 'NYJ', rank: 593, byeWeek: 12),
    Player(id: 'wr185', name: 'Antoine Wesley', position: 'WR', team: 'ARI', rank: 594, byeWeek: 11),
    Player(id: 'wr186', name: 'Cedric Wilson Jr.', position: 'WR', team: 'MIA', rank: 595, byeWeek: 6),
    Player(id: 'wr187', name: 'Marcus Johnson', position: 'WR', team: 'TEN', rank: 596, byeWeek: 5),
    Player(id: 'wr188', name: 'Trent Taylor', position: 'WR', team: 'CIN', rank: 597, byeWeek: 12),
    Player(id: 'wr189', name: 'Stanley Morgan', position: 'WR', team: 'CIN', rank: 598, byeWeek: 12),
    Player(id: 'wr190', name: 'DeAndre Carter', position: 'WR', team: 'LAC', rank: 599, byeWeek: 5),
    Player(id: 'wr191', name: 'Tre Nixon', position: 'WR', team: 'NE', rank: 600, byeWeek: 14),
    Player(id: 'wr192', name: 'Zach Pascal', position: 'WR', team: 'PHI', rank: 601, byeWeek: 14),
    Player(id: 'wr193', name: 'Dez Fitzpatrick', position: 'WR', team: 'TEN', rank: 602, byeWeek: 5),
    Player(id: 'wr194', name: 'Lil\'Jordan Humphrey Jr.', position: 'WR', team: 'NE', rank: 603, byeWeek: 14),
    Player(id: 'wr195', name: 'Darius Davis', position: 'WR', team: 'BAL', rank: 604, byeWeek: 14),
    Player(id: 'wr196', name: 'Jeff Smith', position: 'WR', team: 'NYJ', rank: 605, byeWeek: 12),
    Player(id: 'wr197', name: 'Isaiah Ford', position: 'WR', team: 'MIA', rank: 606, byeWeek: 6),
    Player(id: 'wr198', name: 'Penny Hart', position: 'WR', team: 'SEA', rank: 607, byeWeek: 10),
    Player(id: 'wr199', name: 'Kalija Lipscomb', position: 'WR', team: 'GB', rank: 608, byeWeek: 10),
    Player(id: 'wr200', name: 'River Cracraft', position: 'WR', team: 'MIA', rank: 609, byeWeek: 6),
    Player(id: 'te57', name: 'Tanner Hudson', position: 'TE', team: 'NYG', rank: 610, byeWeek: 11),
    Player(id: 'te58', name: 'Tyler Kroft', position: 'TE', team: 'SF', rank: 611, byeWeek: 9),
    Player(id: 'te59', name: 'Nick Vannett', position: 'TE', team: 'NO', rank: 612, byeWeek: 12),
    Player(id: 'te60', name: 'CJ Uzomah', position: 'TE', team: 'NYJ', rank: 613, byeWeek: 12),
    Player(id: 'qb33', name: 'Jacoby Brissett', position: 'QB', team: 'WAS', rank: 614, byeWeek: 14),
    Player(id: 'qb34', name: 'Jameis Winston', position: 'QB', team: 'CLE', rank: 615, byeWeek: 10),
    Player(id: 'qb35', name: 'Mason Rudolph', position: 'QB', team: 'TEN', rank: 616, byeWeek: 5),
    Player(id: 'qb36', name: 'Tyler Huntley', position: 'QB', team: 'CLE', rank: 617, byeWeek: 10),
    Player(id: 'qb37', name: 'Taylor Heinicke', position: 'QB', team: 'ATL', rank: 618, byeWeek: 12),
    Player(id: 'qb38', name: 'Davis Mills', position: 'QB', team: 'HOU', rank: 619, byeWeek: 14),
    Player(id: 'rb121', name: 'Malcolm Brown', position: 'RB', team: 'LAR', rank: 620, byeWeek: 6),
    Player(id: 'rb122', name: 'Carlos Hyde', position: 'RB', team: 'JAX', rank: 621, byeWeek: 12),
    Player(id: 'rb123', name: 'Samaje Perine Jr.', position: 'RB', team: 'KC', rank: 622, byeWeek: 6),
    Player(id: 'rb124', name: 'Trayveon Williams', position: 'RB', team: 'CIN', rank: 623, byeWeek: 12),
    Player(id: 'rb125', name: 'JaMycal Hasty', position: 'RB', team: 'JAX', rank: 624, byeWeek: 12),
    Player(id: 'rb126', name: 'Spencer Brown', position: 'RB', team: 'CIN', rank: 625, byeWeek: 12),
    Player(id: 'rb127', name: 'Bryce Perkins', position: 'RB', team: 'LAR', rank: 626, byeWeek: 6),
    Player(id: 'rb128', name: 'Jake Funk', position: 'RB', team: 'LAR', rank: 627, byeWeek: 6),
    Player(id: 'wr201', name: 'Josh Gordon', position: 'WR', team: 'TEN', rank: 628, byeWeek: 5),
    Player(id: 'wr202', name: 'Keelan Cole', position: 'WR', team: 'LV', rank: 629, byeWeek: 10),
    Player(id: 'wr203', name: 'John Ross', position: 'WR', team: 'NYG', rank: 630, byeWeek: 11),
    Player(id: 'wr204', name: 'Travis Wilson', position: 'WR', team: 'PIT', rank: 631, byeWeek: 9),
    Player(id: 'wr205', name: 'Cam Johnson', position: 'WR', team: 'NO', rank: 632, byeWeek: 12),
    Player(id: 'wr206', name: 'Damiere Byrd', position: 'WR', team: 'ATL', rank: 633, byeWeek: 12),
    Player(id: 'wr207', name: 'Tavon Austin', position: 'WR', team: 'JAX', rank: 634, byeWeek: 12),
    Player(id: 'wr208', name: 'Cordarrelle Patterson', position: 'WR', team: 'ATL', rank: 635, byeWeek: 12),
    Player(id: 'wr209', name: 'Deonte Harty', position: 'WR', team: 'BUF', rank: 636, byeWeek: 12),
    Player(id: 'wr210', name: 'Tyron Johnson', position: 'WR', team: 'LAC', rank: 637, byeWeek: 5),
  ];
}
