// File generated by FlutterFire CLI.
// Run `flutterfire configure` to regenerate this file with your Firebase project settings.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpqHB3OYtnn4NAEzG1jln2iLqH2PE4Im0',
    appId: '1:31669439721:web:d3399c556c0bcdca7a7478',
    messagingSenderId: '31669439721',
    projectId: 'dyne-fantasy',
    authDomain: 'dyne-fantasy.firebaseapp.com',
    storageBucket: 'dyne-fantasy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpmAyJuKe1JDbanijCxbmSQb_qVWpSOhU',
    appId: '1:31669439721:android:b22877bb634be9dd7a7478',
    messagingSenderId: '31669439721',
    projectId: 'dyne-fantasy',
    storageBucket: 'dyne-fantasy.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDprJWaOzOtcuyeO2ph2q-DeZN61q1RjIo',
    appId: '1:31669439721:ios:afe6801d802bb8b77a7478',
    messagingSenderId: '31669439721',
    projectId: 'dyne-fantasy',
    storageBucket: 'dyne-fantasy.firebasestorage.app',
    iosBundleId: 'com.example.dyne',
  );
}
